version: '3'
services:
  laravel:
    build: 
      context: .
      dockerfile: 'dev.dockerfile'
    container_name: cl-app
    image: cl-app
    ports:
      - 8880:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - base

  base:
    build:
      context: .
      dockerfile: 'common.dockerfile'
    container_name: cl-app-base
    image: base

  nginx:
    build: ./nginx
    container_name: cl-nginx
    ports:
      - 8888:80
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: cl-mysql
    ports:
      - 3333:3306
    volumes:
      - cl-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=contact-line

volumes:
  cl-mysql-data:
    driver: local
